### ISSUE TITLE
fabric-fim Labels assertion error with fabfed policy mismatch

### ISSUE THREAD

**Issue by disprosium8** [fabric-testbed/fabfed#63]
When there is a mismatch between profile attributes in the config and the SENSE provider policy, the fabric network peering setup results in an assertion error:

```
2023-07-18 10:42:07,775 [fabric_network.py:131] [INFO] fabric_network:vlan=None,stitch_port={'site': 'AWS', 'member-of': ['AWS'], 'region': None, 'device_name': 'agg3.ashb.net.internet2.edu', 'local_name': 'TenGigE0/0/0/11/3', 'preference': 200},device=agg3.ashb.net.internet2.edu,site=AWS
2023-07-18 10:42:07,775 [controller.py:119] [ERROR] 
Traceback (most recent call last):
  File "/home/ezra/repos/fabfed/fabfed/controller/controller.py", line 116, in plan
    provider.add_resource(resource=resource.attributes)
  File "/home/ezra/repos/fabfed/fabfed/provider/api/provider.py", line 150, in add_resource
    raise e
  File "/home/ezra/repos/fabfed/fabfed/provider/api/provider.py", line 144, in add_resource
    self.do_add_resource(resource=resource)
  File "/home/ezra/repos/fabfed/fabfed/provider/fabric/fabric_provider.py", line 50, in do_add_resource
    self.slice.add_resource(resource=resource)
  File "/home/ezra/repos/fabfed/fabfed/provider/fabric/fabric_slice.py", line 173, in add_resource
    self._add_network(resource)
  File "/home/ezra/repos/fabfed/fabfed/provider/fabric/fabric_slice.py", line 96, in _add_network
    network_builder.handle_facility_port()
  File "/home/ezra/repos/fabfed/fabfed/provider/fabric/fabric_network.py", line 217, in handle_facility_port
    peer_labels = Labels(ipv4_subnet=peer_subnet,
  File "/home/ezra/VENV/fabfed/lib/python3.9/site-packages/fim/slivers/capacities_labels.py", line 399, in __init__
    self._set_fields(**kwargs)
  File "/home/ezra/VENV/fabfed/lib/python3.9/site-packages/fim/slivers/capacities_labels.py", line 409, in _set_fields
    assert v is not None  # could be strings or lists of strings
AssertionError
```

Reproduce by using the sense-gcp config in `develop` branch with the existing policy file.  Fix by updating the profile attribute in the policy file to match that in the config.fab file.

```sense:                                                                                                                                             
  stitch-port:                                                                                                                                     
...
  group:
...                                                                                                                         
        profile: FABRIC-GCP-INTERCON                                                                                                               
        producer-for:                                                                                                                              
          - fabric/GCP                                           
  ```

**Comment by xi-yang** [comment]
@abessiari This has been updated, correct?

**Comment by abessiari** [comment]
@xi-yang 

yes.
